export const siteConfig = {
  name: "Eros Enterprises",
  legalName: "Eros Enterprises",
  description:
    "Mumbai's trusted partner for decorative lighting, security systems, smart automation, and annual maintenance services. Serving residential and commercial clients since 2009.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://erosenterprises.in",
  ogImage: "/og-image.png",
  ogImageAlt: "Eros Enterprises — Decorative Lighting, Security & Smart Automation, Mumbai",
  phone: "+91 99201 11774",
  phoneRaw: "919920111774",
  email: "info@erosenterprises.in",
  whatsapp: "919920111774",
  address: "Mumbai, Maharashtra, India",
  locality: "Mumbai",
  region: "Maharashtra",
  country: "IN",
  serviceArea: ["Mumbai", "Thane", "Navi Mumbai", "Maharashtra"],
  priceRange: "₹₹",
  businessType: "LocalBusiness",
  foundedYear: 2009,
  tagline: "Lighting with Purpose",
  social: {
    instagram: "https://instagram.com/erosenterprises",
    facebook: "https://facebook.com/erosenterprises",
    linkedin: "https://linkedin.com/company/erosenterprises",
  },
} as const;
